# Generated by Django 3.2.12 on 2022-04-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=10)),
                ('price', models.IntegerField(blank=True)),
                ('algo', models.CharField(max_length=10)),
                ('hashrate', models.FloatField(null=True)),
                ('profit', models.FloatField(null=True)),
                ('power', models.IntegerField(null=True)),
                ('img_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
